service: example-serverless-layer

frameworkVersion: '3'

plugins:
    - serverless-python-requirements
    - serverless-plugin-scripts

provider:
  name: aws
  runtime: python3.11
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  deploymentBucket:
    name: ${ssm:/${self:custom.project-name}-${self:custom.stage}-serverless-bucket}
    blockPublicAccess: true

custom:
  project-name: example
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}
  pythonRequirements:
    dockerizePip: true
    layer:
      name: ${self:custom.project-name}-dependency-layers
  scripts:
    hooks:
      'deploy:finalize': ./scripts/deploy-finalize.sh ${self:custom.pythonRequirements.layer.name}

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'


