service: example-serverless-layer

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  stage: ${self:custom.stage}
  region: ap-northeast-2
  deploymentBucket:
    name: ${ssm:/${self:custom.project-name}-${self:custom.stage}-serverless-bucket}
    blockPublicAccess: true

plugins:
    - serverless-python-requirements
    - serverless-plugin-scripts

custom:
  project-name: example
  stage: ${opt:stage, self:provider.stage}
  region: ap-northeast-2
  pythonRequirements:
    dockerizePip: true
    layer:
      name: ${self:custom.project-name}-dependency-layers
  scripts:
    hooks:
      'deploy:finalize': ./scripts/deploy-finalize.sh ${self:custom.pythonRequirements.layer.name}

package:
  patterns:
      - '!node_modules/**'
#      - '!venv/**'


